#!/usr/bin/python

#
# Foopanel
# 
# Copyright (C) 2005 - 2006, Federico Pelloni <federico.pelloni@gmail.com>
#
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Library General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#

import sys
import os.path

up = os.path.join(os.path.dirname(__file__), "..")

if os.path.exists(os.path.realpath(os.path.join(up, "setup.py"))) and \
   os.path.isdir(os.path.realpath(os.path.join(up, "foopanel"))):
   
    sys.path.insert(0, os.path.realpath(up))
        

import foopanel

if __name__ == "__main__":
	
	try:
		import psyco
		print "Psyco loaded..."
		psyco.log()
		psyco.profile(0.05)
	except ImportError:
		print "No Psyco found."
		
	foopanel.run()

